name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag agrichrono-back:$(date +%s)
    - name: Download built image
      run: docker image save agrichrono-back -o agrichrono-back.docker
    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: agrichrono-back.docker
        # An explicit key for restoring and saving the cache
        key: agrichrono-back
              
